CREATE TABLE IF NOT EXISTS fun_facts (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  fact_text VARCHAR(500) NOT NULL,
  created_by BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_fun_facts_created_at (created_at),
  CONSTRAINT fk_fun_facts_created_by FOREIGN KEY (created_by) REFERENCES admin_accounts (id) ON DELETE SET NULL
) ENGINE=InnoDB;
